# Generated by Django 4.1.2 on 2022-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNewsAndUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsHeading', models.CharField(max_length=256)),
                ('imageData', models.ImageField(default=None, upload_to='news_heading_images/')),
            ],
        ),
    ]
