# Generated by Django 4.1.2 on 2022-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0002_latestnewsandupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.ImageField(default=None, upload_to='course_images/')),
                ('courseName', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
            ],
        ),
    ]
