# Generated by Django 4.1.2 on 2022-10-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0003_coursedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryTitle', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.ImageField(default=None, upload_to='gallery_images/')),
                ('gallery_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medi_app.gallerysections')),
            ],
        ),
    ]
