# Generated by Django 4.1.2 on 2022-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0004_gallerysections_galleryimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.CharField(max_length=20)),
                ('joining_time', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=50)),
                ('student_DOB', models.CharField(max_length=20)),
                ('student_mother_name', models.CharField(max_length=50)),
                ('student_mother_occup', models.CharField(max_length=50)),
                ('student_father_name', models.CharField(max_length=50)),
                ('student_father_occup', models.CharField(max_length=50)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_caste', models.CharField(max_length=20)),
                ('presentAddress', models.CharField(max_length=50)),
                ('permanentAddress', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('mother_tongue', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('emailId', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('last_attended_school', models.CharField(max_length=30)),
                ('last_attended_school_qual', models.CharField(max_length=30)),
                ('year_of_passing', models.CharField(max_length=10)),
                ('selectedCourse', models.CharField(max_length=20)),
                ('fee_schedule', models.CharField(max_length=10)),
                ('tobe_payed', models.CharField(max_length=50)),
                ('tobe_Qual', models.CharField(max_length=30)),
                ('imageData', models.ImageField(default=None, upload_to='students_images/')),
            ],
        ),
    ]
