# Generated by Django 4.1.2 on 2022-10-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0005_studentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='student_caste',
        ),
    ]
