# Generated by Django 4.1.2 on 2022-10-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0007_studentdetails_student_caste_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='student_caste_category',
        ),
    ]
